series: Basic OpenGL with GLFW
title: Fragment Shaders
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Add different colors to each vertex in the fragment shader.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Vertex Shaders